logo: # add logo name
title: Recetas - Ernesto Vázquez
description: > # this means to ignore newlines until "baseurl:"
  Que viva la comida
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://recetas.ernestovazquez.es" # the base hostname & protocol for your site, e.g. http://example.com

# Banner settings
video: mountains.mp4 # add banner video. Add your video file to the folder video
banner-title: Ernesto Vázquez # add banner title
banner-desc: Esto no es una web de cocina # add banner description

# Author settings
author-pic: face.jpg # your photo
author-name: Ernesto Vázquez # your name
about-author: DevOps Engineer # about author
email: vazquezgarciaernesto@gmail.com # your email
#phone: (496)-169-6557 # your pnone number
website: https://ernestovazquez.es # you website

# Social link
#google_url: https://ernestovazquez.es   # add url link
#twitter_url:   # add url link
#instagram_url: # add url link
#pinterest_url: # add url link
#dribbble_url:  # add url link
#facebook_url:  # add url link

# Disqus
#discus_identifier: mr-brown # add your discus identifier.  Not your username.  To get this, register your forum here with a unique ID: https://disqus.com/admin/create/

# Newsletter
#mailchimp: # add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Tracker
analytics:

# Paginate
paginate: 12
paginate_path: /page:num/

# Build settings
markdown: kramdown
plugins_dir:
  - jekyll-paginate
  - jekyll-sitemap

gems:
  - jekyll-paginate
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
